version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map the port if needed
    depends_on:
      - backend
    # Add other configuration options as needed

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # Map the port if needed
    # Add other configuration options as needed
